name: condominium_app
description: "Sistema inteligente de condominio con IA"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  shared_preferences: ^2.5.3
  fl_chart: ^0.65.0
  material_design_icons_flutter: ^7.0.0
  cached_network_image: ^3.4.1
  flutter_stripe: ^11.3.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.0.0
  
  # ðŸ”¥ Firebase - Notificaciones Push
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/iconApp.png"
  adaptive_icon_background: "#0EA5A3"
  adaptive_icon_foreground: "assets/iconApp.png"